### ISSUE TITLE
Signia not reactive on nextjs

### ISSUE THREAD

**Issue by judicaelandria** [tldraw/signia#58]
using the same examples as this but using nextjs [tldraw-examples](https://github.com/tldraw/tldraw-examples/blob/main/src/examples/4-custom-ui/CustomUiExample.tsx); Even if we track the components, the value is not reactive at all;

**Comment by ds300** [comment]
Ah I see what's going on here. Signia uses some global state which is being reproduced in your case because you have multiple versions of signia in your nextjs bundle.

You can use pnpm's `overrides` field to make sure that every package that uses signia is using the same version: 

<img width="921" alt="image" src="https://user-images.githubusercontent.com/1242537/225328583-50febeb5-e04e-42ff-ba97-cca81792028e.png">

**Comment by judicaelandria** [comment]
I used the same version earlier, but I updated it as you said but still the same issue

**Comment by ds300** [comment]
argh sorry, i read the pnpm docs wrong. it should be "resolutions" not "overrides". then make sure you run `rm -rf node_modules && pnpm i` after

**Comment by judicaelandria** [comment]
yay, it's working! thanks so much David! oh and your PR does fix an issue in react too
