### ISSUE TITLE
Why is `useValue` implemented as it is?

### ISSUE THREAD

**Issue by smoothbricker** [tldraw/signia#88]
Hi there,

I'm working on a Event + State management library, building on top of Signia and trying to understand the internals better.

Somehow I was reading the docs but skipped over `useValue` and tried to implement re-rendering of signals without the library user having to use `track()`.

So I wrote this:

```ts
export const useSignal = <S extends Signal<any, any>>(name: string, signal: S) => {
  const [state, setState] = useState(signal.value);
  useEffect(() => react(name, () => setState(signal.value)), []);
  return state;
};
```

What's wrong with this? It seems to work just fine in a small demo app, but `useValue` seems to do a lot more things... Would like to know why :-)

**Comment by SomeHats** [comment]
There are two main differences between our `useValue` and yours:
1. We support passing a function instead of a signal. This is shorthand for `useValue(useMemo(() => computed(() => doSomething()), []))`
2. Use [`useSyncExternalStore`](https://react.dev/reference/react/useSyncExternalStore) instead of an effect for subscriptions. This covers a bunch of edge cases that the effect method doesn't e.g. what happens if the value of the signal changes after your component renders, but before the effect is fired? there are more details on wha useSyncExternalStore is about in the react docs

**Comment by flow-danny** [comment]
But wouldn't that call setState in the signia react and cause a rerender?

The effect is just a mount/unmount to signia's react.

Like I said I'm trying to understand the internals of Signia better and why this would break. I suppose it could be more performant if a signal changes multiple times between a render, but doesnt setState do the same, scheduling a rerender?

The react docs don't really help with this.
